[package]
name = "wasm-coredump-rewriter"
version = "0.1.23"
edition = "2021"
authors = ["Sven Sauleau <sven@sauleau.com>"]
license = "MIT"
keywords = ["wasm", "rewrite", "coredump"]
repository = "https://github.com/xtuc/wasm-coredump/tree/main/bin/rewriter"
description = "Rewrite Wasm binaries to add coredump support"
include = ["src", "runtime.wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.1"
log = "0.4.17"
wasm-parser = { path = "../../lib/parser", version = "0.1.23" }
wasm-printer = { path = "../../lib/printer", version = "0.1.23" }
core-wasm-ast = { path = "../../lib/ast", version = "0.1.23" }
clap = { version = "4.2.5", features = ["derive"] }
